### ISSUE TITLE
Short Cut Button or similar

### ISSUE THREAD

**Issue by SphaeroX** [Fede91/vs-chatgpt#1]
It would be great to have a shortcut button to call chat gpt immediately, or at least make a field via right click so that you can call the input field.

**Comment by Fede91** [comment]
Hi @SphaeroX , nice idea! Of course, I will add this feature!

**Comment by Fede91** [comment]
Hi @SphaeroX , a just released the version 1.1.0!
In this update I added the shortcut and the possibility to send the text selected in the editor to ChatGPT!

**Comment by SphaeroX** [comment]
Thank you I have made it immediately as Marco on my keyboard
