### ISSUE TITLE
Can you show how to set OpenAI key? Screenshot is better

### ISSUE THREAD

**Issue by jimwangzx** [Fede91/vs-chatgpt#3]

**Comment by Fede91** [comment]
Hi @jimwangzx , I just released version 1.3.0 where I added the walkthroughs that illustrates the steps to follow to generate and set up the OpenAI Api key.

**Comment by jimwangzx** [comment]
I reinstalled but I don't find the walkthrough

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/44415773/213167259-475dda2d-f809-4138-801a-381918aba7a6.png">

**Comment by jimwangzx** [comment]
Fount it. Thanks. Please close
