### ISSUE TITLE
jsdoc comment on rightclick menu, or configure rightclick by user

### ISSUE THREAD

**Issue by SphaeroX** [Fede91/vs-chatgpt#4]
For me, a very important function in the shortcuts when I right click would be the following:

> INPUT:   getRecipePreparation(_id) {    this.preparation = apiGetPreparation(this.id);    return this.preparation;  }  write me a jsdoc for this function

Output:

> /**
>  * Retrieves the preparation instructions for a given recipe.
>  * @param {string} _id - The ID of the recipe.
>  * @returns {string} The preparation instructions for the recipe.
>  */
> function getRecipePreparation(_id) { ... }

now of course the question is would it make sense to make this pure? 
JSDoc is explicitly for javascript, can you make it so that you can edit this right-click menu independently using a config file? 

Then everyone can configure the same, that whould be nice!

**Comment by Fede91** [comment]
Hi @SphaeroX , thank you for the suggestion. It doesn't seem that the VSCode APIs allow for this type of configuration, but I will find a way! For now, I am releasing the new version 1.4.0 that will allow you to generate JsDoc for javascript and typescript files!
