### ISSUE TITLE
add gpt-3.5-turbo

### ISSUE THREAD

**Issue by SphaeroX** [Fede91/vs-chatgpt#5]
Could you add the new API so that it can be selected in the settings?

gpt-3.5-turbo

**Comment by SphaeroX** [comment]
But you also have to take care that the new URL is used for the chat model 

> https://api.openai.com/v1/chat/completions

**Comment by Fede91** [comment]
Hi @SphaeroX , thanks for the info, i just released the version 1.5.0!
